version: '3.9'

services:
  sisconis-db:
    image: postgres:16-alpine
    container_name: sisconis-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - sisconis-db-data:/var/lib/postgresql/data
    networks:
      - sisconis-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sisconis" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sisconis-db-data:
    name: sisconis-db-data

networks:
  sisconis-net:
